name: publish_conda

on:
  push:
    tags:
      - '*.*.*-release'
      - '*.*-release'
    
jobs:
  publish-conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: build-conda-packages
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda install conda-build anaconda-client conda-verify
        conda config --add channels conda-forge
        conda config --set anaconda_upload yes
        cd conda
        conda build --token "$ANACONDA_TOKEN" .
